### ISSUE TITLE
Sound not working 

### ISSUE THREAD

**Issue by NeonzGamingYT** [hyperio546/termux-xfce#2]
Can we have chrome instead of firefox? I tried to install chrome but it doesn't work.
Also playing audio, the sound does not come out

If you have any idea about this, tell me

**Comment by kinoosaki** [comment]
Uhh sound is still a wip (I have to figure out how pulseaudo works and test it). As for chrome it's not possible to run it in Termux natively (this project uses all the native tools ported by the termux team this is why it's actually faster) but you can export DISPLAY and run it via proot.

**Comment by NeonzGamingYT** [comment]
> Uhh sound is still a wip (I have to figure out how pulseaudo works and test it). As for chrome it's not possible to run it in Termux natively (this project uses all the native tools ported by the termux team this is why it's actually faster) but you can export DISPLAY and run it via proot.

Ah ok, thx for that ☺️

**Comment by kinoosaki** [comment]
> > Uhh sound is still a wip (I have to figure out how pulseaudo works and test it). As for chrome it's not possible to run it in Termux natively (this project uses all the native tools ported by the termux team this is why it's actually faster) but you can export DISPLAY and run it via proot.
> 
> Ah ok, thx for that ☺️

Don't worry about the sound I'll implement it in January or Feb. It's still in work. My phone hasn't got the Android 13 update so I can't disable the phantom killer which is causing issues running the server. This is why I haven't been able to test it and have only done small changes. Once I get the update which I'll get in Jan or Feb then I'll start working on sound.

**Comment by kinoosaki** [comment]
My phone got android 13 and I was able to disable phantom easily and I have tested it today. Now I'll see what I can do about sound.

**Comment by kinoosaki** [comment]
Sound works now
